
# REST Client tests on http://localhost:8080/ server
# Use docker-composer up --build to launch the test server 
@baseUrl = http://localhost:8080
### dev
#@token = 0x8276d5e4133eba2043a2a9fccc55284c1243f1d4
### prod thelao
@token = 0x8f56682a50becb1df2fb8136954f2062871bc7fc
### prod flamingo
#@token = 0x43310bd1c8f261ee7b9025662207ed95329aa193

### Health Check (root)
GET {{baseUrl}}/

### Health Check (api)
GET {{baseUrl}}/api

### Migration(api)
PUT {{baseUrl}}/api/{{token}}/migrate HTTP/1.1

### Create a General Proposal 1
POST {{baseUrl}}/api/message HTTP/1.1
Content-Type: application/json

{"address":"0xEd7B3f2902f2E1B17B027bD0c125B674d293bDA0","msg":"{\"payload\":{\"name\":\"Testing a general proposal 2\",\"body\":\"Test test test\",\"choices\":[\"Yes\",\"No\"],\"start\":1603301264,\"end\":1603304864,\"snapshot\":7409598,\"metadata\":{\"private\":false,\"type\":\"Governance\",\"subType\":\"General\"}},\"timestamp\":\"1603301263\",\"token\":\"0x8276d5e4133eba2043a2a9fccc55284c1243f1d4\",\"type\":\"proposal\",\"version\":\"0.1.2\"}","sig":"0x3850ca29c7c92487a96fa816abd0164f5bfccde25516e4fcb2cf81bd1a7d756b7d70c143b6a99b9444511327835ca3e15f9eef93ba2eac29cd9a53c9aeb728441c"}

### Create Governance Proposal 2
POST {{baseUrl}}/api/message HTTP/1.1
Content-Type: application/json

{"address":"0xEd7B3f2902f2E1B17B027bD0c125B674d293bDA0","msg":"{\"payload\":{\"name\":\"Test Governance Proposal Submission\",\"body\":\"This is a test to see if the Governance Proposal submission is working fine and get stored into our Postgres SQL db.\",\"choices\":[\"Yes\",\"No\"],\"start\":1603230537,\"end\":1603234137,\"snapshot\":7404887,\"metadata\":{\"private\":false,\"type\":\"Governance\",\"subType\":\"Governance\"}},\"timestamp\":\"1603230536\",\"token\":\"0x8276d5e4133eba2043a2a9fccc55284c1243f1d4\",\"type\":\"proposal\",\"version\":\"0.1.2\"}","sig":"0x87c5c72e2009aa09887057f3a1bb59fb289ecccd94fd85518ab224ab62df79aa3a68793243ea4ed64fb6f25e64d7fe353cdab28075f4b5378dc55416e1fd4b461b"}

### Get All proposals based on token
GET {{baseUrl}}/api/{{token}}/proposals HTTP/1.1

### Vote YES on General Proposal 1
POST {{baseUrl}}/api/message HTTP/1.1
Content-Type: application/json

{"address":"0xEd7B3f2902f2E1B17B027bD0c125B674d293bDA0","msg":"{\"payload\":{\"choice\":1,\"proposal\":\"QmTdejAMkvSGaYJf345rnN5tG6jHdMyXjrRZY6Bu8UXeVr\",\"metadata\":{\"memberAddress\":\"0xed7b3f2902f2e1b17b027bd0c125b674d293bda0\"}},\"timestamp\":\"1603301300\",\"token\":\"0x8276d5e4133eba2043a2a9fccc55284c1243f1d4\",\"type\":\"vote\",\"version\":\"0.1.2\"}","sig":"0xe44506143777b347364fadc6155b231e1535fc4b34b90f76f29a8313aec3a422353b12b7e255ba24d5ff2e10e93e5c060eb737b6720e871e325a24186223a1f91c"}


### Vote NO on General Proposal 1
POST {{baseUrl}}/api/message HTTP/1.1
Content-Type: application/json

{"address":"0xEd7B3f2902f2E1B17B027bD0c125B674d293bDA0","msg":"{\"payload\":{\"choice\":2,\"proposal\":\"QmTdejAMkvSGaYJf345rnN5tG6jHdMyXjrRZY6Bu8UXeVr\",\"metadata\":{\"memberAddress\":\"0xed7b3f2902f2e1b17b027bd0c125b674d293bda0\"}},\"timestamp\":\"1603301319\",\"token\":\"0x8276d5e4133eba2043a2a9fccc55284c1243f1d4\",\"type\":\"vote\",\"version\":\"0.1.2\"}","sig":"0x8f44396c30ad33cf5b9b13a082a44cf537b7be0e8ecaeb625f18c19452d36efa1c8c2cf561c044d55b4c08387aa66bb2d5773204847031c0c82d2302a64513791b"}

### Get proposal votes
GET {{baseUrl}}/api/{{token}}/proposal/QmYWyqesuVTvngwKFhhmAzDrLbJTJYav4d3P21swF4HiYd  HTTP/1.1

"QmQs1mnLfkZHPKzaiinUw6fvS1FCSpWUcWD7yF7LhG9rZM" -> "QmZeMUwErFFopM1nhvqPKEhEMoyUXsHZwNQ9DdjjA4qQbo",
"QmagPitbzYXh39yzcd1tu9W2RzFBA49P4qGiSVQkdFm3Lf" -> "QmSbgyAxq1jnwsrt3vYFm9GaGrJAdTmm6HN17rxeUA3PbN",
"QmVBJBqa1xx3T2MBCvFoqnHKTUw2NhUXo6WRD4cXuXENJk" -> "QmXBpZ2fFUR5s3uEiuSCdr1XF3HnSyQYev5qxMG6L9swS1",
"Qmd4AngpoK2dkUcAXcw76jfWnsXGAp8VKN1pxAKNmg4iki" -> "QmbguBpXbyvGEPXJEDBLGRgyTbaKhjZoi8pPmXokYgym9V",
"QmeTLYqnrnxR9q4vskShMhkgmUiaX23FGeNLgRcwzCoXiR" -> "Qmakd8TYdkQ4c6rPyUmAeD5eC8PomDDUwmibns1pVwEz5Y",
"QmWWDM8rcrSjXVo4ygFg9jgqvjvq7AdrF66spACeaLgBpH" -> "QmYWyqesuVTvngwKFhhmAzDrLbJTJYav4d3P21swF4HiYd"