
# REST Client tests on http://localhost:8080/ server
# Use docker-composer up --build to launch the test server 
@baseUrl = http://localhost:8080

### Health Check (root)
GET {{baseUrl}}/

### Health Check (api)
GET {{baseUrl}}/api

### Create a General Proposal 1
POST {{baseUrl}}/api/message HTTP/1.1
Content-Type: application/json

{"address":"0xEd7B3f2902f2E1B17B027bD0c125B674d293bDA0","msg":"{\"payload\":{\"name\":\"Test General Proposal Submission\",\"body\":\"This is a test\",\"choices\":[\"Yes\",\"No\"],\"start\":1603216589,\"end\":1603220189,\"snapshot\":7403957,\"metadata\":{\"private\":false,\"type\":\"Governance\",\"subType\":\"General\"}},\"timestamp\":\"1603216588\",\"token\":\"0x8276d5e4133eba2043a2a9fccc55284c1243f1d4\",\"type\":\"proposal\",\"version\":\"0.1.2\"}","sig":"0xd40441460ed6662f6959740321a2d6248f202b3830535874dc8e7fcec2d0441456f0f6fe7fc46037f2c50ee920a668f9991c1cf837084e511e376f13479422391c"}

### Create Governance Proposal 2
POST {{baseUrl}}/api/message HTTP/1.1
Content-Type: application/json

{"address":"0xEd7B3f2902f2E1B17B027bD0c125B674d293bDA0","msg":"{\"payload\":{\"name\":\"Test Governance Proposal Submission\",\"body\":\"This is a test to see if the Governance Proposal submission is working fine and get stored into our Postgres SQL db.\",\"choices\":[\"Yes\",\"No\"],\"start\":1603230537,\"end\":1603234137,\"snapshot\":7404887,\"metadata\":{\"private\":false,\"type\":\"Governance\",\"subType\":\"Governance\"}},\"timestamp\":\"1603230536\",\"token\":\"0x8276d5e4133eba2043a2a9fccc55284c1243f1d4\",\"type\":\"proposal\",\"version\":\"0.1.2\"}","sig":"0x87c5c72e2009aa09887057f3a1bb59fb289ecccd94fd85518ab224ab62df79aa3a68793243ea4ed64fb6f25e64d7fe353cdab28075f4b5378dc55416e1fd4b461b"}

### Get All proposals based on token
GET {{baseUrl}}/api/0x8276d5e4133eba2043a2a9fccc55284c1243f1d4/proposals HTTP/1.1

### Vote YES on Governance Proposal 2

POST {{baseUrl}}/api/message HTTP/1.1
Content-Type: application/json

{"address":"0xEd7B3f2902f2E1B17B027bD0c125B674d293bDA0","msg":"{\"payload\":{\"choice\":1,\"proposal\":\"Qmecn8LiZey9SMtscFMKtdC1mwtrCApEk1siX1vjkX31QN\",\"metadata\":{\"memberAddress\":\"0xed7b3f2902f2e1b17b027bd0c125b674d293bda0\"}},\"timestamp\":\"1603230712\",\"token\":\"0x8276d5e4133eba2043a2a9fccc55284c1243f1d4\",\"type\":\"vote\",\"version\":\"0.1.2\"}","sig":"0x5a6e06f5d2a3a4f94935bd09833934b437b4422a04d94aa6e1b7bd24ec47bf6366766f806442eace9fce32572f5005ebadd305f4256fe35807ff188f200bb8651b"}

### Get proposal votes
GET {{baseUrl}}/api/0x8276d5e4133eba2043a2a9fccc55284c1243f1d4/proposal/0xEd7B3f2902f2E1B17B027bD0c125B674d293bDA0  HTTP/1.1

## expected output