
# REST Client tests on http://localhost:8080/ server
# Use docker-composer up --build to launch the test server 
#@baseUrl = http://localhost:8080
@baseUrl = https://testnet.snapshot.page

### Health Check (root)
GET {{baseUrl}}/

### Health Check (api)
GET {{baseUrl}}/api

### Get proposals

GET {{baseUrl}}}/api/0x8276d5e4133eba2043a2a9fccc55284c1243f1d4/proposals

### Send a msg (api)
#POST {{baseUrl}}/api/message HTTP/1.1
#content-type: application/json

#{}